### PR TITLE
Demo rest api

### PR DESCRIPTION
**Pull request by agrinnecta**
Can you check this commit, please?

### CODE REVIEW

**Review by lincner — COMMENTED** [review]
README file is almost empty. Please, add useful information to the file.

**Comment by agrinnecta** [comment]
> README file is almost empty. Please, add useful information to the file.

Ok, I will do it today. Thank you.

**Comment by lincner** [comment]
#1 

@agrinnecta Add GitHub setup to README as well, for example:
### Git / GitHub setup
* Follow these instructions to [setup Git / GitHub](https://help.github.com/articles/set-up-git/)
* To get you acquainted with Git following site is a good [starting point](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics)

Also, it would be nice to use constants instead of strings for the names in the getNames test:

```
@Test
	void getNamesShouldReturnExpectedNames() {
		Set<String> resultNames = new HashSet<String>(Arrays.asList("Ana","Peter"));
		RestDemoController restDemoController = new RestDemoController();
		assertArrayEquals(resultNames.toArray(), restDemoController.getNames().toArray());
	}
```

**Review by lincner — CHANGES_REQUESTED** [review]
Add GitHub setup to the README file

**Review by lincner — APPROVED** [review]

**Pull request merged**
